### ISSUE TITLE
Email alert for non-users

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#50] opened 2017-02-23 01:49 UTC
Request from conference.

If we:

a) add all existing pastors to teams - even if they haven't / aren't /won't use the system and assign them to their current church/team.

Then can we:

b. When we do an auto-assign, it sends the pastor an email with all the contact data (e.g. name, contact method, etc.) and a reminder/invitation to log-in and activate their account?

This means, for example, the youth department only enters data once - instead of still having to send out excel spreadsheets to those not yet using AH

**Comment by brettdonald** [comment] 2017-05-22 05:41
Duplicate of 77

**Closed by brettdonald** 2017-05-22 05:41 UTC
