### ISSUE TITLE
Church transfer process

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#54] opened 2017-02-23 02:04 UTC
We need a seamless process to transfer all contacts from one user to another - i.e. when new pastors come in

**Comment by cristiansc** [comment] 2017-02-23 02:04
Is there a way to add a setting so pastors can change what team they belong to themselves?

**Comment by brettdonald** [comment] 2017-05-22 05:35
Duplicate of 89,90

**Closed by brettdonald** 2017-05-22 05:35 UTC
