### ISSUE TITLE
Bulk import messing up states

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#35] opened 2017-02-07 03:15 UTC
Tried to do a bulk upload. All the data in the 'state' column was "NSW". However, and quite randomly as I can't detect a pattern, a number (perhaps 20-30%) of the uploads had their state changed to ACT in the system - not sure why

**Comment by cristiansc** [comment] 2017-02-07 03:26
Seems more like 40-50% of contacts after having gone through them all

**Comment by danlewis** [comment] 2017-02-07 03:42
can you send me the CSV used for the upload via email - feel free to strip out the name, phone number and address line 1 fields. All other fields should be kept the same

**Comment by danlewis** [comment] 2017-02-08 00:02
This is a duplicate of issue #39 which resolves the issue

**Closed by danlewis** 2017-02-08 00:02 UTC
